name: PR Validation

on:
  push:
    branches: [main]
    paths-ignore:
      - .schema/**
      - .vscode/**
      - docs/**
      - "*.md"
      - LICENSE
      - .git*
  pull_request:
    branches: [main]
    paths-ignore:
      - .schema/**
      - .vscode/**
      - docs/**
      - "*.md"
      - LICENSE
      - .git*

concurrency:
  group: ${{ (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) || 'push-main' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      - name: Generate i18n files
        run: yarn i18n

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
